#data_pattern: '(?P<name>[0-9A-Za-z_]+)_(?P<idx>005)_(?P<type>.*)\.tif$'
data_pattern: '(?P<name>[0-9A-Za-z_]+)_(?P<idx>\d+)_(?P<type>RGB).*\.tif$'
ensemble:
  method: average # voting, weighted average

models:
  model:
    path: MODELPATH # Expandad automat
    builder: hugin.models.unet.unetv15:unet_v15
    type: keras
    window_size: [256, 256]
    stride_size: 100
    match_id: '.*'
    batch_size: 20
    swap_axes: True
    rescale: null
    mapping:
      inputs:
        - [ "RGB", 1 ]
        - [ "RGB", 2 ]
        - [ "RGB", 3 ]
      target:
        - [ "GTI", 1 ]
